[package]
name = "c001_starfield"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
femtovg = "0.2.8"
glutin = "0.28.0"
rand = "0.8.4"
winit = "0.26.0"

[dependencies.helpers]
path = "../helpers"
